name: test and merge
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env:
      NODE_ENV: test
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      DIRECT_DATABASE_URL: ${{ secrets.DIRECT_DATABASE_URL }}
      NEXT_PUBLIC_URL: ${{ secrets.NEXT_PUBLIC_URL }}
      STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
      WEBSITE_ADMIN_EMAIL: ${{ secrets.WEBSITE_ADMIN_EMAIL }}
      WEBSITE_ADMIN_PASSWORD: ${{ secrets.WEBSITE_ADMIN_PASSWORD }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm install -g pnpm && pnpm install
    - name: Generate Prisma Client
      run: pnpm prisma generate --no-engine
    - name: Install Playwright Browsers
      run: pnpm exec playwright install --with-deps
    - name: Run Playwright tests
      run: DEBUG=pw:api pnpm exec playwright test
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
  automerge:
    needs: test
    env:
      GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      MERGE_LABELS: "automerge,!wip"
      MERGE_REMOVE_LABELS: "automerge"
    runs-on: ubuntu-latest
    permissions: 
      contents: write
      pull-requests: write
    steps:
    - uses: "pascalgn/automerge-action@v0.16.2"
